version: '3.8'

services:
  db:
    container_name: db-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"

  war:
    container_name: war
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - global:/app/
    depends_on:
      db:
        condition: service_started

  web:
    container_name: web
    image: tomcat:8-jdk8
    working_dir: /app/
    ports:
      - '8080:8080'
    volumes:
      - global:/usr/local/tomcat/webapps/
    depends_on:
      war:
        condition: service_completed_successfully

volumes:
  global: